### ISSUE TITLE
Notification Specification

### ISSUE THREAD

**Issue by vritant24** [for-each-org/PUDM-server#2]
## Endpoints

**GET**: `/notification/`

accept: Nothing

return: 
```
body: {
  status: <Bool>,
  notifications: [
    {
      id: <Int>, 
      time: <UNIX Time>,
      content: <String>,
      group: <Int>
    },
    ...
  ]
}
```

---

**POST** : `/notification/new`

accept:
```
body: {
  time: <UNIX Time>,
  content: <String>,
  group: <Int>,
}
```
return: 
```
body: {
  status: <Bool>
}
```

---

**EDIT** : `/notification/edit`

accept:
```
body: {
  ID: <int>
  time: <UNIX Time>,
  content: <String>,
  group: <Int>
}
```
return: 
```
body: {
  status: <Bool>
}
```

---

**DELETE** : `/notification/delete`

accept:
```
body: {
  id: <Int>
}
```
return: 
```
body: {
  status: <Bool>
}
```

**Comment by claytn** [comment]
@vritant24 In regards to the first `/notification` endpoint: Could we send along with the GET request the device ID? This way the notification filtering would be done on the back-end and not front-end. Also, we wouldn't have to send as much data back to the user.

**Comment by drewatk** [comment]
Closing in favor of Firebase architecture
