### ISSUE TITLE
Firebase Schema Setup

### ISSUE THREAD

**Issue by claytn** [for-each-org/PUDM-server#6]
### Users
| Email (PK)      | Name           | Check-In  | Bag |
| ------------- |:-------------:|:-----:|-----:|
| String      | String | Bool | Bool |

___

### Device
| Device ID | Device Token  | Group  |
|:-------------:|:-------------:|:-----:|
| Int     | Int | String  | Int |

___

### Group 
| ID (PK)      | Color | 
|:-------------:|:-------------:| 
|Int|String|

___

### Notifications
| ID (PK)      | Time to Notify | Notification (Content) | Group  | Status  |
|:-------------:|:-------------:|:-----:|:-----:|:-----:|
| Int     | UnixTime | String  | Int | Bool |

___

**Comment by drewatk** [comment]
I think this should be the updated Devices schema. We'll have a UUID identify the device, and the token is what we need to give APNs to send the notification.

### Devices

| UUID     | Device Token  | Group  |
|:-------------:|:-------------:|:-----:|
| Int     | Int | String  | Int |

**Comment by drewatk** [comment]
We've decided to nest groups and devices, example:
```
{
  groupid: {
    deviceid: {
      token: "string"
    }, ...
  }, ...
}
```

**Comment by vritant24** [comment]
After going through firebase guides, we've finalized on the structure of the data being stored, and it will be so:

```
users = {
  id: {
    email: String,
    name: String,
    checkIn: Bool,
    bag: Bool
  },
 ...
}
```

```
groups = {
  0: String,
  1: String,
  ...
  8: String
}
```

```
Devices = {
  0: {   //groupID
    device_id: token,
    ...
  },
  ...
}
```

```
Notifications = {
  id: {
    content: String,
    group: int,
    time: int,
    status: Bool
  },
  ...
}
```

**Comment by drewatk** [comment]
Notification IDs are strings

This issue will be used in #10
